---
title: Edney Directory
timezone: UTC
collections:
  floor-eight:
    title: Floor Eight
    output: true
  floor-five:
    title: Floor Five
    output: true
  floor-four:
    title: Floor Four
    output: true
  floor-nine:
    title: Floor Nine
    output: true
  floor-one:
    title: Floor One
    output: true
  floor-seven:
    title: Floor Seven
    output: true
  floor-six:
    title: Floor Six
    output: true
  floor-three:
    title: Floor Three
    output: true
  floor-two:
    title: Floor Two
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
